import Rasp

-- Every public theorem is audited, together with the specified matrix step.
#print axioms Rasp.momentumSequence_zero
#print axioms Rasp.momentumSequence_succ
#print axioms Rasp.centered_split
#print axioms Rasp.disagreement_sign_invariant
#print axioms Rasp.noiseOperator_quadratic
#print axioms Rasp.noiseOperator_rank_le
#print axioms Rasp.objective_expansion
#print axioms Rasp.objective_line
#print axioms Rasp.solves_vi
#print axioms Rasp.vi_solves
#print axioms Rasp.solves_iff_vi
#print axioms Rasp.exists_solution
#print axioms Rasp.strong_gap
#print axioms Rasp.solution_unique
#print axioms Rasp.firm_stability
#print axioms Rasp.lipschitz_signal
#print axioms Rasp.alignment
#print axioms Rasp.disagreement_antitone
#print axioms Rasp.zero_signal
#print axioms Rasp.descent_upper_model
#print axioms Rasp.diag₂_feasible
#print axioms Rasp.inner_diag₂
#print axioms Rasp.counterexample_optimal
#print axioms Rasp.counterexample_unconstrained
#print axioms Rasp.counterexample_projected
#print axioms Rasp.counterexample_gap
#print axioms Rasp.mem_spectralBall
#print axioms Rasp.spectralBall_convex
#print axioms Rasp.spectralBall_compact
#print axioms Rasp.zero_mem_spectralBall
#print axioms Rasp.matrix_exists_unique
#print axioms Rasp.matrixStep_solves
#print axioms Rasp.matrixStep_feasible
#print axioms Rasp.asOperator_apply
#print axioms Rasp.entry_le_opNorm
#print axioms Rasp.frobenius_inner
#print axioms Rasp.isotropicStep_solves
#print axioms Rasp.isotropicStep_vi
#print axioms Rasp.project_minimizes_distance
#print axioms Rasp.isotropicStep_eq_project
#print axioms Rasp.dualStep_vi
#print axioms Rasp.root_solves
#print axioms Rasp.solution_is_dualStep
#print axioms Rasp.exists_root
#print axioms Rasp.feedback_strong_mono
#print axioms Rasp.root_unique
#print axioms Rasp.feedback_error_bound
#print axioms Rasp.iid_split_second_moment
#print axioms Rasp.directional_noise_identity
#print axioms Rasp.matrixStep
#print axioms Rasp.approx_vi_gap
#print axioms Rasp.approx_vi_distance
#print axioms Rasp.residual_roundoff_certificate
#print axioms Rasp.zero_penalty_eq_projection
#print axioms Rasp.dualStep_lipschitz
#print axioms Rasp.approximate_feedback_error
#print axioms Rasp.feedback_initial_bracket
#print axioms Rasp.feedback_root_interval
#print axioms Rasp.radial_feasibility
#print axioms Rasp.interval_midpoint_error
#print axioms Rasp.bisection_step_error
#print axioms Rasp.bisection_width_step
#print axioms Rasp.adaptive_example_realized_zero
#print axioms Rasp.adaptive_example_step_second_moment
#print axioms Rasp.adaptive_example_fresh_risk_quarter
