import Creso

-- Audit all public project theorems.
#print axioms Creso.radialMatrix_feasible
#print axioms Creso.guardedLibrary_feasible
#print axioms Creso.mix_zero
#print axioms Creso.mix_one
#print axioms Creso.mix_feasible
#print axioms Creso.progress_mix
#print axioms Creso.certificate_quadratic
#print axioms Creso.bestFraction_mem
#print axioms Creso.bestFraction_maximizes
#print axioms Creso.segment_optimal
#print axioms Creso.uniform_certificate
#print axioms Creso.vertex_certificate_error
#print axioms Creso.selected_oracle_bound
#print axioms Creso.exists_finite_best
#print axioms Creso.exists_matrix_decision
#print axioms Creso.exists_guarded_matrix_decision
#print axioms Creso.selected_nonnegative_progress
#print axioms Creso.deflation_recovers_signal
#print axioms Creso.certified_descent
#print axioms Creso.active_matrix_muon_gap
#print axioms Creso.active_matrix_candidates_feasible
#print axioms Creso.dependent_matrix_certificate_counterexample
#print axioms Creso.strict_matrix_interpolation_gain
#print axioms Creso.mem_spectralBall
#print axioms Creso.spectralBall_convex
#print axioms Creso.spectralBall_compact
#print axioms Creso.zero_mem_spectralBall
#print axioms Creso.asOperator_apply
#print axioms Creso.entry_le_opNorm
#print axioms Creso.frobenius_inner
#print axioms Creso.diag₂_feasible
#print axioms Creso.inner_diag₂
#print axioms Creso.radial_feasibility
#print axioms Creso.finite_chebyshev
#print axioms Creso.finite_union_bound
#print axioms Creso.simultaneous_moment_bound
#print axioms Creso.relative_trace_upper
#print axioms Creso.trace_upper_failure_mass
#print axioms Creso.zero_trace_exact
#print axioms Creso.squared_sum_envelope
#print axioms Creso.finite_split_envelope
#print axioms Creso.finite_inner_trace_bound
#print axioms Creso.finite_directional_envelope
#print axioms Creso.two_stage_failure_bound
#print axioms Creso.adaptive_certificate_failure_mass
#print axioms Creso.finite_sum_second_moment
#print axioms Creso.finite_mean_second_moment
