name = "rasp"
version = "0.1.0"
defaultTargets = ["Rasp"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4"
rev = "7974e751bece493b6ff508039423ca9fa2452fa8"

[[lean_lib]]
name = "Rasp"
