name = "creso"
version = "0.2.0"
defaultTargets = ["Creso"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4"
rev = "7974e751bece493b6ff508039423ca9fa2452fa8"

[[lean_lib]]
name = "Creso"
